name: Build VS Code Extension
on: push
permissions:
    contents: write
jobs:
    build:
        name: "Build VS Code Extension"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Package extension3
              run: openssl rand -base64 12 >> "extension.vsix"

            - name: echo random
              run: cat /proc/sys/kernel/random/uuid

            - name: Create File Hash
              uses: actions/github-script@v7
              with:
                  script: |
                      const crypto = require('crypto');
                      const fs = require('fs');
                      const fileBuffer = fs.readFileSync("extension.vsix");
                      const hash = crypto.createHash('sha256').update(fileBuffer);
                      fs.writeFileSync("extension.hash", hash.digest('hex'));

            - name: Upload extension vsix as artifact
              uses: actions/upload-artifact@v4
              with:
                  name: "extension.vsix"
                  path: "extension.vsix"

            - name: Upload extension hash as artifact
              uses: actions/upload-artifact@v4
              with:
                  name: "extension.hash"
                  path: "extension.hash"

            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                  files: |
                      extension.hash
                      extension.vsix
                  draft: false
                  tag_name: "1.94"
                  prerelease: false
