name: Build VS Code Extension
on: push
permissions:
    contents: write
jobs:
    build:
        name: "Build VS Code Extension"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup project environment
              uses: actions/github-script@v7
              with:
                  script: require('./.github/env-setup-ci.js')({github});

            - name: Package extension
              run: echo "test" >> extension.vsix

            - name: Upload extension vsix as artifact
              uses: actions/upload-artifact@v4
              with:
                  name: "extension.vsix"
                  path: "extension.vsix"

            - name: Upload extension hash as artifact
              uses: actions/upload-artifact@v4
              with:
                  name: "extension.hash"
                  path: "extension.hash"

            - name: Check if the versions match
              uses: actions/github-script@v7
              if: startsWith(github.ref, 'refs/heads/release/')
              with:
                  script: |
                      const ref = context.payload.ref;
                      console.log("------", ref);
                      const version1 = context.payload.ref.replace('refs/heads/release/', '');
                      const version2 = require('./package.json').version;
                      if (version1 !== version2) {
                        core.setFailed(`Version mismatch: ${version1} !== ${version2}`);
                      }

            - name: Release
              uses: softprops/action-gh-release@v2
              if: startsWith(github.ref, 'refs/heads/release/')
              with:
                  files: |
                      extension.hash
                      extension.vsix
                  draft: false
                  tag_name: "1.94"
                  prerelease: false
